background="#fbf1c7"
text="#654735"
subtle="#b47109"
warning-text="#c14a4a"
text-special-one="#45707a"
text-special-two="#945e80"
top-bar-background="#654735"
top-bar-text="#fbf1c7"
status-bar-background="#654735"
status-bar-text="#fbf1c7"
status-bar-view-background="#4c7a5d"
status-bar-view-text="#fbf1c7"
list-selected-background="#654735"
list-selected-text="#fbf1c7"
command-text="#654735"
list-selected-inactive-background="#945e80"
list-selected-inactive-text="#fbf1c7"
controls-text="#654735"
controls-highlight="#945e80"
autocomplete-background="#fbf1c7"
autocomplete-text="#654735"
autocomplete-selected-background="#4c7a5d"
autocomplete-selected-text="#fbf1c7"
button-color-one="#654735"
button-color-two="#fbf1c7"
timeline-name-background="#fbf1c7"
timeline-name-text="#654735"
